import React, { useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { Screen } from '../components/Screen';
import { Button } from '../components/Button';
import { Field } from '../components/Field';
import { theme } from '../theme';
export function ForgotPasswordScreen({navigation}:any){const[step,setStep]=useState(1);const[email,setEmail]=useState('');const[code,setCode]=useState('');const[pass,setPass]=useState('');const[confirm,setConfirm]=useState('');
 return <Screen><View style={styles.page}><Text style={styles.kicker}>{step===1?'RECUPERAR ACESSO':step===2?'VERIFICAÇÃO':'NOVA SENHA'}</Text><Text style={styles.title}>{step===1?'Esqueceu':step===2?'Cheque':'Redefina'}</Text><Text style={[styles.title,styles.italic]}>{step===1?'a senha?':step===2?'seu e-mail':'sua senha'}</Text><Text style={styles.sub}>{step===1?'Informe o e-mail da sua conta e enviaremos um código de verificação.':step===2?`Enviamos um código de 6 dígitos para ${email||'seu e-mail'}.`:'Escolha uma senha segura para proteger sua conta.'}</Text>{step===1&&<><Field label="E-MAIL" value={email} onChangeText={setEmail} autoCapitalize="none" keyboardType="email-address" placeholder="seu@email.com"/><Button label="ENVIAR CÓDIGO" onPress={()=>setStep(2)}/></>}{step===2&&<><Field label="CÓDIGO" value={code} onChangeText={setCode} keyboardType="number-pad" maxLength={6} placeholder="000000" style={styles.code}/><Button label="VERIFICAR" onPress={()=>setStep(3)}/></>}{step===3&&<><Field label="NOVA SENHA" value={pass} onChangeText={setPass} secureTextEntry placeholder="Mínimo 8 caracteres"/><Field label="CONFIRMAR SENHA" value={confirm} onChangeText={setConfirm} secureTextEntry placeholder="Repita a senha"/><Button label="SALVAR NOVA SENHA" disabled={!pass||pass!==confirm} onPress={()=>navigation.navigate('Login')}/></>}<Pressable onPress={()=>navigation.navigate('Login')}><Text style={styles.back}>Voltar ao login</Text></Pressable></View></Screen>}
const styles=StyleSheet.create({page:{padding:28,paddingTop:30},kicker:{color:theme.colors.accent,fontSize:10,fontWeight:'900',letterSpacing:1.4},title:{color:theme.colors.text,fontFamily:theme.fonts.display,fontSize:43,lineHeight:40,marginTop:12},italic:{fontStyle:'italic'},sub:{color:theme.colors.muted,fontSize:13,lineHeight:20,marginTop:15,marginBottom:26},code:{height:60,borderWidth:1,borderColor:theme.colors.surface2,borderBottomWidth:1,borderRadius:6,paddingHorizontal:14,fontSize:23,letterSpacing:8,textAlign:'center'},back:{color:theme.colors.muted,textAlign:'center',fontSize:11,marginTop:22}});
