import React,{useEffect,useRef,useState}from'react';
import{Image,Pressable,ScrollView,StyleSheet,Text,View}from'react-native';
import{Ionicons}from'@expo/vector-icons';
import{Screen}from'../components/Screen';
import{Header}from'../components/Header';
import{Footer}from'../components/Footer';
import{Button}from'../components/Button';
import{ProductCard}from'../components/ProductCard';
import{HERO_SLIDES}from'../data';
import{getProducts}from'../database';
import{Product}from'../types';
import{theme}from'../theme';
export function HomeScreen({navigation}:any){const[slide,setSlide]=useState(0);const[products,setProducts]=useState<Product[]>([]);const timer=useRef<ReturnType<typeof setInterval>|null>(null);useEffect(()=>{timer.current=setInterval(()=>setSlide(v=>(v+1)%HERO_SLIDES.length),4500);getProducts().then(setProducts).catch(console.error);return()=>{if(timer.current)clearInterval(timer.current)}},[]);const next=()=>setSlide(v=>(v+1)%HERO_SLIDES.length);const prev=()=>setSlide(v=>(v-1+HERO_SLIDES.length)%HERO_SLIDES.length);const highlights=products.length?[...products,...products.slice(0,3)]:[];return <Screen><Header navigation={navigation} onSearch={()=>navigation.navigate('Search')}/><View style={styles.hero}><View style={styles.heroImageWrap}><Image source={{uri:HERO_SLIDES[slide].image}} style={styles.heroImage}/><View style={styles.imageShade}/><Pressable onPress={prev} style={[styles.arrow,{left:9}]}><Ionicons name="chevron-back" size={26} color={theme.colors.text}/></Pressable><Pressable onPress={next} style={[styles.arrow,{right:9}]}><Ionicons name="chevron-forward" size={26} color={theme.colors.text}/></Pressable></View><View style={styles.heroText}><Text style={styles.heroTitle}>Encontre</Text><Text style={styles.heroTitle}>Peças</Text><Text style={[styles.heroTitle,styles.italic]}>únicas</Text><Text style={styles.heroSub}>Descubra tesouros vintage e peças exclusivas</Text><View style={styles.cta}><Button label="COMPRE AGORA" onPress={()=>navigation.navigate('Main',{screen:'Produtos'})}/></View></View></View><View style={styles.novidades}><Text style={styles.sectionTitle}>NOVIDADES</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.marquee}>{highlights.map((p,i)=><ProductCard key={`${p.id}-${i}`} product={p} compact onPress={()=>navigation.navigate('ProductDetail',{id:p.id})}/>)}</ScrollView></View><Footer/></Screen>}
const styles=StyleSheet.create({hero:{paddingHorizontal:16,paddingTop:24,paddingBottom:34},heroImageWrap:{width:'100%',aspectRatio:1.333,borderRadius:theme.radius.md,overflow:'hidden',backgroundColor:theme.colors.surface2,position:'relative'},heroImage:{width:'100%',height:'100%'},imageShade:{...StyleSheet.absoluteFillObject,backgroundColor:'rgba(0,0,0,0.12)'},arrow:{position:'absolute',top:'46%',width:36,height:36,borderRadius:18,backgroundColor:'rgba(15,15,15,0.55)',alignItems:'center',justifyContent:'center'},heroText:{alignItems:'center',paddingTop:26},heroTitle:{color:theme.colors.text,fontFamily:theme.fonts.display,fontSize:54,lineHeight:49,textAlign:'center'},italic:{fontStyle:'italic'},heroSub:{color:theme.colors.muted,fontSize:13,lineHeight:20,textAlign:'center',marginTop:14},cta:{width:156,marginTop:18},novidades:{borderTopWidth:2,borderTopColor:theme.colors.accent,paddingTop:20,paddingBottom:10},sectionTitle:{color:theme.colors.text,fontWeight:'900',fontSize:11,letterSpacing:2,textAlign:'center',marginBottom:18},marquee:{paddingHorizontal:16,gap:12}});
