import React, { useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { Screen } from '../components/Screen';
import { Button } from '../components/Button';
import { Field } from '../components/Field';
import { saveUser, setSession } from '../storage';
import { theme } from '../theme';
export function LoginScreen({navigation}:any){const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[show,setShow]=useState(false);const[remember,setRemember]=useState(false);
 async function login(){await saveUser({name:'Pedro Henrique',email:email.trim()||'pedro@email.com'});await setSession(true);navigation.navigate('Main',{screen:'Perfil'});}
 return <Screen><View style={styles.page}><View style={styles.editorial}><Text style={styles.kicker}>GALERIA SELETA</Text><Text style={styles.editorialTitle}>Seu estilo,</Text><Text style={styles.editorialTitle}>sua</Text><Text style={[styles.editorialTitle,styles.italic]}>identidade</Text><View style={styles.line}/></View><View><Text style={styles.kicker}>BEM-VINDO DE VOLTA</Text><Text style={styles.title}>Entrar</Text><Field label="E-MAIL" value={email} onChangeText={setEmail} autoCapitalize="none" keyboardType="email-address" placeholder="seu@email.com"/><View style={styles.passwordLabel}><Text style={styles.label}>SENHA</Text><Pressable onPress={()=>navigation.navigate('ForgotPassword')}><Text style={styles.forgot}>Esqueceu a senha?</Text></Pressable></View><View style={styles.password}><Field label="" value={password} onChangeText={setPassword} secureTextEntry={!show} placeholder="Sua senha"/><Pressable onPress={()=>setShow(v=>!v)} style={styles.eye}><Ionicons name={show?'eye-off-outline':'eye-outline'} size={18} color={theme.colors.muted}/></Pressable></View><Pressable onPress={()=>setRemember(v=>!v)} style={styles.remember}><Ionicons name={remember?'checkbox':'square-outline'} size={17} color={remember?theme.colors.accent:theme.colors.muted}/><Text style={styles.rememberText}>Lembrar de mim</Text></Pressable><Button label="ENTRAR" onPress={login}/><View style={styles.or}><View style={styles.orLine}/><Text style={styles.orText}>ou</Text><View style={styles.orLine}/></View><Button label="CRIAR CONTA" secondary onPress={()=>navigation.navigate('Register')}/></View></View></Screen>}
const styles=StyleSheet.create({page:{padding:28},editorial:{paddingBottom:24},kicker:{color:theme.colors.accent,fontSize:10,fontWeight:'900',letterSpacing:1.4},editorialTitle:{color:theme.colors.text,fontFamily:theme.fonts.display,fontSize:49,lineHeight:45,marginTop:10},italic:{fontStyle:'italic'},line:{width:72,height:2,backgroundColor:theme.colors.accent,marginTop:24},title:{color:theme.colors.text,fontFamily:theme.fonts.display,fontSize:36,marginTop:7,marginBottom:24},passwordLabel:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},label:{color:theme.colors.muted,fontSize:10,fontWeight:'900',letterSpacing:.7},forgot:{color:theme.colors.accent,fontSize:10},password:{position:'relative'},eye:{position:'absolute',right:0,bottom:24,width:30,height:30,alignItems:'center',justifyContent:'center'},remember:{flexDirection:'row',alignItems:'center',gap:7,marginTop:-2,marginBottom:18},rememberText:{color:theme.colors.muted,fontSize:11},or:{flexDirection:'row',alignItems:'center',gap:10,marginVertical:18},orLine:{flex:1,height:1,backgroundColor:theme.colors.line},orText:{color:theme.colors.muted,fontSize:11},
});
