import React, { useEffect, useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { Screen } from '../components/Screen';
import { theme } from '../theme';
import { getOrders } from '../storage';
import { Order } from '../types';
const money=(v:number)=>v.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
export function OrdersScreen({navigation}:any){const[orders,setOrders]=useState<Order[]>([]);const load=()=>getOrders().then(setOrders);useEffect(()=>{load();const u=navigation.addListener('focus',load);return u},[navigation]);return <Screen><View style={styles.page}><Text style={styles.title}>Meus pedidos</Text>{orders.length===0?<View style={styles.empty}><Ionicons name="receipt-outline" size={40} color={theme.colors.accent}/><Text style={styles.emptyTitle}>Ainda não há pedidos</Text><Text style={styles.emptyText}>Quando você fizer uma compra, seus pedidos aparecerão aqui.</Text></View>:<View style={styles.list}>{orders.map(o=><Pressable key={o.id} onPress={()=>navigation.navigate('OrderDetail',{orderId:o.id})} style={styles.card}><View style={styles.cardTop}><Text style={styles.id}>Pedido {o.id}</Text><Ionicons name="chevron-forward" size={18} color={theme.colors.muted}/></View><Text style={styles.date}>{o.date}</Text><View style={styles.cardBottom}><Text style={[styles.status,o.status==='ENTREGUE'&&styles.delivered]}>{o.status}</Text><Text style={styles.total}>{money(o.total)}</Text></View></Pressable>)}</View>}</View></Screen>}
const styles=StyleSheet.create({page:{padding:20},title:{color:theme.colors.text,fontFamily:theme.fonts.display,fontSize:39},list:{gap:12,marginTop:22},card:{backgroundColor:theme.colors.surface,borderRadius:9,padding:16},cardTop:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},id:{color:theme.colors.text,fontSize:13,fontWeight:'800'},date:{color:theme.colors.muted,fontSize:10,marginTop:7},cardBottom:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginTop:16},status:{color:theme.colors.accent,fontSize:9,fontWeight:'900',letterSpacing:.7},delivered:{color:theme.colors.success},total:{color:theme.colors.accent,fontFamily:theme.fonts.display,fontSize:20},empty:{alignItems:'center',paddingTop:120},emptyTitle:{color:theme.colors.text,fontFamily:theme.fonts.display,fontSize:28,marginTop:18},emptyText:{color:theme.colors.muted,fontSize:12,lineHeight:18,textAlign:'center',marginTop:8,maxWidth:290}});
