import React, { useEffect, useState } from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { Screen } from '../components/Screen';
import { getOrders } from '../storage';
import { Order } from '../types';
import { theme } from '../theme';
const money=(v:number)=>v.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
export function OrderDetailScreen({route}:any){const[o,setO]=useState<Order|null>(null);useEffect(()=>{getOrders().then(xs=>setO(xs.find(x=>x.id===route.params.orderId)||null))},[route.params.orderId]);if(!o)return <Screen><View style={styles.page}><Text style={styles.muted}>Pedido não encontrado.</Text></View></Screen>;return <Screen><View style={styles.page}><Text style={styles.kicker}>PEDIDO {o.id}</Text><Text style={styles.title}>Detalhes do pedido</Text><Text style={styles.date}>REALIZADO EM {o.date}</Text><View style={styles.status}><Text style={styles.kicker}>STATUS</Text><Text style={styles.statusTitle}>{o.status}</Text><Text style={styles.muted}>Acompanhe as próximas atualizações pelo app.</Text></View><Text style={styles.section}>ITENS</Text>{o.items.map(i=><View key={`${i.id}-${i.size}`} style={styles.item}><View style={{flex:1}}><Text style={styles.itemName}>{i.name}</Text><Text style={styles.muted}>{i.quantity} × {money(i.discountPrice??i.price)} · Tamanho {i.size}</Text></View><Text style={styles.itemPrice}>{money((i.discountPrice??i.price)*i.quantity)}</Text></View>)}<Text style={styles.section}>ENDEREÇO DE ENTREGA</Text><View style={styles.address}><Text style={styles.itemName}>{o.address.street}</Text><Text style={styles.muted}>{o.address.city} — {o.address.state} · {o.address.zip}</Text></View><View style={styles.totalRow}><Text style={styles.totalLabel}>TOTAL</Text><Text style={styles.total}>{money(o.total)}</Text></View></View></Screen>}
const styles=StyleSheet.create({page:{padding:20},kicker:{color:theme.colors.accent,fontSize:10,fontWeight:'900',letterSpacing:1.3},title:{color:theme.colors.text,fontFamily:theme.fonts.display,fontSize:36,lineHeight:40,marginTop:8},date:{color:theme.colors.muted,fontSize:9,letterSpacing:.7,marginTop:8},status:{backgroundColor:theme.colors.surface,borderRadius:9,padding:17,marginTop:22},statusTitle:{color:theme.colors.text,fontFamily:theme.fonts.display,fontSize:24,marginTop:8,marginBottom:4},muted:{color:theme.colors.muted,fontSize:11,lineHeight:18},section:{color:theme.colors.muted,fontSize:9,fontWeight:'900',letterSpacing:1.3,marginTop:25,marginBottom:9},item:{backgroundColor:theme.colors.surface,borderRadius:8,padding:15,flexDirection:'row',alignItems:'center',marginBottom:8},itemName:{color:theme.colors.text,fontSize:12,fontWeight:'800',marginBottom:5},itemPrice:{color:theme.colors.text,fontFamily:theme.fonts.display,fontSize:18},address:{backgroundColor:theme.colors.surface,borderRadius:8,padding:15},totalRow:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginTop:26},totalLabel:{color:theme.colors.text,fontWeight:'900',fontSize:11},total:{color:theme.colors.accent,fontFamily:theme.fonts.display,fontSize:25}});
