import React,{useEffect,useState}from'react';
import{ActivityIndicator,Image,Pressable,StyleSheet,Text,View}from'react-native';
import{Ionicons}from'@expo/vector-icons';
import{Screen}from'../components/Screen';
import{Header}from'../components/Header';
import{Button}from'../components/Button';
import{ProductCard}from'../components/ProductCard';
import{getProductById,getProducts}from'../database';
import{Product}from'../types';
import{getCart,saveCart}from'../storage';
import{theme}from'../theme';
const money=(v:number)=>v.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
export function ProductDetailScreen({route,navigation}:any){const[product,setProduct]=useState<Product|null>(null);const[related,setRelated]=useState<Product[]>([]);const[size,setSize]=useState('M');const[qty,setQty]=useState(1);const[added,setAdded]=useState(false);useEffect(()=>{Promise.all([getProductById(route.params.id),getProducts()]).then(([p,all])=>{setProduct(p);setRelated(all.filter(x=>x.id!==route.params.id).slice(0,2));setQty(1);setAdded(false)}).catch(console.error)},[route.params.id]);if(!product)return <Screen><Header navigation={navigation}/><View style={styles.loading}><ActivityIndicator color={theme.colors.accent}/></View></Screen>;const activeProduct=product;const finalPrice=activeProduct.discountPrice??activeProduct.price;async function addCart(go=false){const cart=await getCart();const i=cart.findIndex(x=>x.id===activeProduct.id&&x.size===size);if(i>=0)cart[i].quantity+=qty;else cart.push({...activeProduct,size,quantity:qty});await saveCart(cart);setAdded(true);if(go)navigation.navigate('Cart')}return <Screen><Header navigation={navigation} onSearch={()=>navigation.navigate('Search')}/><View style={styles.page}><Image source={{uri:activeProduct.image}} style={styles.image}/><Text style={styles.category}>{activeProduct.category.toUpperCase()}</Text><Text style={styles.name}>{activeProduct.name}</Text><Text style={styles.price}>{money(finalPrice)}</Text><Text style={styles.description}>{activeProduct.description}</Text><Text style={styles.label}>TAMANHO</Text><View style={styles.options}>{['P','M','G','GG'].map(s=><Pressable key={s} onPress={()=>setSize(s)} style={[styles.size,size===s&&styles.sizeActive]}><Text style={styles.sizeText}>{s}</Text></Pressable>)}</View><View style={styles.qtyRow}><Text style={styles.label}>QUANTIDADE</Text><View style={styles.qty}><Pressable onPress={()=>setQty(v=>Math.max(1,v-1))}><Ionicons name="remove" size={17} color={theme.colors.text}/></Pressable><Text style={styles.qtyValue}>{qty}</Text><Pressable onPress={()=>setQty(v=>Math.min(activeProduct.stock,v+1))}><Ionicons name="add" size={17} color={theme.colors.text}/></Pressable></View></View><View style={styles.actions}><Button label={added?'✓ ADICIONADO AO CARRINHO':'ADICIONAR AO CARRINHO'} disabled={activeProduct.stock<=0} onPress={()=>addCart()}/><Button label="COMPRAR AGORA ›" secondary disabled={activeProduct.stock<=0} onPress={()=>addCart(true)}/></View><Text style={styles.relatedTitle}>VOCÊ TAMBÉM PODE GOSTAR</Text><View style={styles.related}>{related.map(p=><ProductCard key={p.id} product={p} onPress={()=>navigation.replace('ProductDetail',{id:p.id})}/>)}</View></View></Screen>}
const styles=StyleSheet.create({page:{padding:16},loading:{minHeight:420,alignItems:'center',justifyContent:'center'},image:{width:'100%',height:380,borderRadius:theme.radius.md,backgroundColor:theme.colors.surface2},category:{color:theme.colors.accent,fontSize:10,fontWeight:'900',letterSpacing:1.4,marginTop:20},name:{color:theme.colors.text,fontFamily:theme.fonts.display,fontSize:38,lineHeight:42,marginTop:3},price:{color:theme.colors.accent,fontFamily:theme.fonts.display,fontSize:28,fontWeight:'700',marginTop:5},description:{color:theme.colors.muted,fontSize:13,lineHeight:20,marginTop:14,marginBottom:24},label:{color:theme.colors.muted,fontSize:10,fontWeight:'900',letterSpacing:1},options:{flexDirection:'row',gap:8,marginTop:10},size:{width:50,height:42,borderRadius:4,backgroundColor:theme.colors.surface2,alignItems:'center',justifyContent:'center'},sizeActive:{backgroundColor:theme.colors.accent},sizeText:{color:theme.colors.text,fontWeight:'800'},qtyRow:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginTop:22},qty:{height:42,minWidth:116,paddingHorizontal:13,borderWidth:1,borderColor:theme.colors.surface2,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},qtyValue:{color:theme.colors.text,fontWeight:'800'},actions:{gap:9,marginTop:22},relatedTitle:{color:theme.colors.text,fontSize:10,fontWeight:'900',letterSpacing:1.5,marginTop:34,marginBottom:16},related:{flexDirection:'row',justifyContent:'space-between'}});
