import React, { useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { Screen } from '../components/Screen';
import { Button } from '../components/Button';
import { Field } from '../components/Field';
import { saveUser, setSession } from '../storage';
import { theme } from '../theme';
export function RegisterScreen({navigation}:any){const[name,setName]=useState('');const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[confirm,setConfirm]=useState('');const[accepted,setAccepted]=useState(false);const[show,setShow]=useState(false);
 async function submit(){if(password!==confirm)return;await saveUser({name:name||'Pedro Henrique',email:email||'pedro@email.com'});await setSession(true);navigation.navigate('Main',{screen:'Perfil'});}
 return <Screen><View style={styles.page}><Text style={styles.kicker}>NOVA CONTA</Text><Text style={styles.title}>Crie sua</Text><Text style={styles.title}>conta</Text><Text style={[styles.title,styles.italic]}>exclusiva</Text><Text style={styles.sub}>Acesse peças únicas e ofertas especiais.</Text><Field label="NOME" value={name} onChangeText={setName} placeholder="Seu nome"/><Field label="E-MAIL" value={email} onChangeText={setEmail} autoCapitalize="none" placeholder="seu@email.com"/><Field label="CPF" placeholder="000.000.000-00" keyboardType="number-pad"/><Field label="TELEFONE" placeholder="(11) 90000-0000" keyboardType="phone-pad"/><View style={styles.pass}><Field label="SENHA" value={password} onChangeText={setPassword} secureTextEntry={!show} placeholder="Mínimo 8 caracteres"/><Pressable onPress={()=>setShow(v=>!v)} style={styles.eye}><Ionicons name={show?'eye-off-outline':'eye-outline'} size={18} color={theme.colors.muted}/></Pressable></View><Field label="CONFIRMAR SENHA" value={confirm} onChangeText={setConfirm} secureTextEntry={!show} placeholder="Repita a senha"/>{password!==confirm&&confirm.length>0&&<Text style={styles.error}>As senhas não coincidem.</Text>}<Pressable onPress={()=>setAccepted(v=>!v)} style={styles.check}><Ionicons name={accepted?'checkbox':'square-outline'} size={17} color={accepted?theme.colors.accent:theme.colors.muted}/><Text style={styles.checkText}>Li e aceito os Termos de Uso e a Política de Privacidade.</Text></Pressable><Button label="CRIAR CONTA" disabled={!accepted||password!==confirm} onPress={submit}/><Pressable onPress={()=>navigation.navigate('Login')}><Text style={styles.loginLink}>Já tem cadastro? Entrar</Text></Pressable></View></Screen>}
const styles=StyleSheet.create({page:{padding:28},kicker:{color:theme.colors.accent,fontSize:10,fontWeight:'900',letterSpacing:1.4},title:{color:theme.colors.text,fontFamily:theme.fonts.display,fontSize:48,lineHeight:43,marginTop:8},italic:{fontStyle:'italic'},sub:{color:theme.colors.muted,fontSize:12,lineHeight:18,marginTop:12,marginBottom:24},pass:{position:'relative'},eye:{position:'absolute',right:0,bottom:23},check:{flexDirection:'row',alignItems:'flex-start',gap:8,marginBottom:18},checkText:{flex:1,color:theme.colors.muted,fontSize:10,lineHeight:15},error:{color:theme.colors.error,fontSize:10,marginTop:-10,marginBottom:10},loginLink:{color:theme.colors.accent,textAlign:'center',fontSize:11,fontWeight:'700',marginTop:18},});
