import React, { useEffect, useMemo, useState } from 'react';
import { Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { Screen } from '../components/Screen';
import { ProductCard } from '../components/ProductCard';
import { CATEGORIES } from '../data';
import { getProducts } from '../database';
import { Product } from '../types';
import { theme } from '../theme';
export function SearchScreen({navigation}:any){const[q,setQ]=useState('');const[products,setProducts]=useState<Product[]>([]);useEffect(()=>{getProducts().then(setProducts).catch(console.error)},[]);const results=useMemo(()=>q.trim()?products.filter(p=>`${p.name} ${p.description} ${p.category}`.toLowerCase().includes(q.toLowerCase())):[],[products,q]);return <Screen><View style={styles.page}><View style={styles.top}><Pressable onPress={()=>navigation.goBack()} hitSlop={8}><Ionicons name="chevron-back" size={25} color={theme.colors.text}/></Pressable><Text style={styles.kicker}>BUSCAR</Text><View style={{width:25}}/></View><View style={styles.search}><Ionicons name="search-outline" size={18} color={theme.colors.muted}/><TextInput value={q} onChangeText={setQ} autoFocus placeholder="O que procura?" placeholderTextColor={theme.colors.muted} style={styles.input}/>{q.length>0&&<Pressable onPress={()=>setQ('')}><Ionicons name="close-circle" size={18} color={theme.colors.muted}/></Pressable>}</View>{!q?<><Text style={styles.section}>CATEGORIAS</Text><View style={styles.categories}>{CATEGORIES.map(c=><Pressable key={c.id} onPress={()=>setQ(c.name)} style={styles.category}><Text style={styles.categoryText}>{c.name}</Text></Pressable>)}</View></>:<><Text style={styles.result}>{results.length} resultado{results.length===1?'':'s'} para “{q}”</Text>{results.length===0?<Text style={styles.noResult}>Nenhuma peça encontrada.</Text>:<View style={styles.grid}>{results.map(p=><ProductCard key={p.id} product={p} onPress={()=>navigation.navigate('ProductDetail',{id:p.id})}/>)}</View>}</>}</View></Screen>}
const styles=StyleSheet.create({page:{padding:16},top:{height:40,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},kicker:{color:theme.colors.text,fontSize:10,fontWeight:'900',letterSpacing:1.4},search:{height:52,backgroundColor:theme.colors.surface,borderRadius:7,paddingHorizontal:13,flexDirection:'row',alignItems:'center',marginTop:12},input:{flex:1,color:theme.colors.text,fontSize:13,marginLeft:9,paddingVertical:0},section:{color:theme.colors.muted,fontSize:10,fontWeight:'900',letterSpacing:1.2,marginTop:30,marginBottom:10},categories:{flexDirection:'row',flexWrap:'wrap',gap:8},category:{width:'48%',backgroundColor:theme.colors.surface2,borderRadius:5,padding:13},categoryText:{color:theme.colors.text,fontSize:11,fontWeight:'700'},result:{color:theme.colors.muted,fontSize:11,marginTop:22,marginBottom:14},grid:{flexDirection:'row',flexWrap:'wrap',justifyContent:'space-between'},noResult:{color:theme.colors.muted,textAlign:'center',marginTop:70,fontSize:13}});
